### ISSUE TITLE
Does ha-bridge-5.3.1rc1-patch.jar work with java 11 as well?

### ISSUE THREAD

**Issue by amyth1884** [roadsnail/ha-bridge-5.3.1rc1-patch#1]
currently using https://github.com/bwssytems/ha-bridge/releases/download/v5.3.0/ha-bridge-5.3.0-java11.jar

does the patch work on java11 as well ?

**Comment by roadsnail** [comment]
Hi, I don't know the answer to that question. Using java8 here.

FYI. bwssystems has just released an 'official' release candidate. See https://github.com/bwssytems/ha-bridge/issues/1243#issuecomment-724228394

**Comment by bwssytems** [comment]
I may have to compile one for Java11

**Comment by bwssytems** [comment]
Here is the Java11 compiled jar 

https://github.com/bwssytems/ha-bridge/releases/download/v5.3.1RC2/ha-bridge-5.3.1RC2.java11.jar

**Comment by amyth1884** [comment]
Thank you

**Comment by roadsnail** [comment]
Closing this issue, as bwssystems has provided Java11 compiled jar available from the linked repository.
